// <auto-generated />
using System;
using ApiPrueba.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPrueba.Migrations
{
    [DbContext(typeof(ClinicaFisioterapiaBD))]
    [Migration("20251121154528_Afiliacion")]
    partial class Afiliacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiPrueba.Models.AlertaAgenda", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaGenerada")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCita")
                        .HasColumnType("int");

                    b.Property<int>("IdTerapeuta")
                        .HasColumnType("int");

                    b.Property<bool>("Resuelta")
                        .HasColumnType("bit");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdCita");

                    b.HasIndex("IdTerapeuta", "Resuelta");

                    b.ToTable("AlertasAgenda");
                });

            modelBuilder.Entity("ApiPrueba.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEntidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAuditoria");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("ApiPrueba.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Confirmada")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionProgramadaMin")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HoraFinReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraInicioReal")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdTerapeuta")
                        .HasColumnType("int");

                    b.Property<int?>("IdTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioCita")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TerapeutaId")
                        .HasColumnType("int");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("int");

                    b.HasKey("IdCita");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdTratamiento");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TerapeutaId");

                    b.HasIndex("TratamientoId");

                    b.HasIndex("IdTerapeuta", "CheckIn");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("ApiPrueba.Models.ContactoEmergencia", b =>
                {
                    b.Property<int>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContacto"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonoAlterno")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TelefonoPrincipal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdPaciente");

                    b.ToTable("ContactosEmergencia");
                });

            modelBuilder.Entity("ApiPrueba.Models.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdFactura");

                    b.ToTable("DetalleFactura");
                });

            modelBuilder.Entity("ApiPrueba.Models.Diagnostico", b =>
                {
                    b.Property<int>("IdDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiagnostico"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDiagnostico")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdTerapeuta")
                        .HasColumnType("int");

                    b.Property<int?>("IdTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("TerapeutaId")
                        .HasColumnType("int");

                    b.HasKey("IdDiagnostico");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdTerapeuta");

                    b.HasIndex("IdTratamiento");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("ApiPrueba.Models.DisponibilidadTerapeuta", b =>
                {
                    b.Property<int>("IdDisponibilidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDisponibilidad"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdTerapeuta")
                        .HasColumnType("int");

                    b.Property<string>("TipoAmbiente")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdDisponibilidad");

                    b.HasIndex("IdTerapeuta", "DiaSemana");

                    b.ToTable("DisponibilidadesTerapeutas");
                });

            modelBuilder.Entity("ApiPrueba.Models.DocumentoPaciente", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioSubida")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TamañoArchivo")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdPaciente", "FechaSubida");

                    b.ToTable("DocumentosPaciente");
                });

            modelBuilder.Entity("ApiPrueba.Models.EPS", b =>
                {
                    b.Property<int>("EPSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EPSId"));

                    b.Property<string>("NombreEPS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EPSId");

                    b.ToTable("Epss");
                });

            modelBuilder.Entity("ApiPrueba.Models.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipo"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ApiPrueba.Models.EquipoSesion", b =>
                {
                    b.Property<int>("IdEquipoSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipoSesion"));

                    b.Property<int>("CantidadUsada")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipo")
                        .HasColumnType("int");

                    b.Property<int?>("IdProtocolo")
                        .HasColumnType("int");

                    b.Property<int?>("IdProtocoloTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdEquipoSesion");

                    b.HasIndex("IdEquipo");

                    b.HasIndex("IdProtocoloTratamiento");

                    b.HasIndex("IdProtocolo", "IdEquipo")
                        .IsUnique()
                        .HasFilter("[IdProtocolo] IS NOT NULL");

                    b.ToTable("EquiposSesion");
                });

            modelBuilder.Entity("ApiPrueba.Models.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ApiPrueba.Models.EvolucionPaciente", b =>
                {
                    b.Property<int>("IdEvolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvolucion"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdEvolucion");

                    b.HasIndex("IdPaciente", "Fecha");

                    b.ToTable("EvolucionesPaciente");
                });

            modelBuilder.Entity("ApiPrueba.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("IdTratamiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<decimal?>("Impuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RutaArchivoPDF")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdTratamiento");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("ApiPrueba.Models.HistorialMedico", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Alergias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AntecedentesHeredofamiliares")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CirugiasAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnfermedadesCronicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Habitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("MedicamentosActuales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("HistorialMedicos");
                });

            modelBuilder.Entity("ApiPrueba.Models.NotaSesion", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNota"));

                    b.Property<string>("CambioDiagnostico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Recomendaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdNota");

                    b.HasIndex("IdCita");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("PacienteId");

                    b.ToTable("NotasSesion");
                });

            modelBuilder.Entity("ApiPrueba.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoIdentidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique()
                        .HasFilter("[DocumentoIdentidad] IS NOT NULL");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("TipoPersona").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ApiPrueba.Models.PlanTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetallesSesiones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdTerapeuta")
                        .HasColumnType("int");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("Objetivos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("TerapeutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdTerapeuta");

                    b.HasIndex("IdTratamiento");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("PlanTratamientos");
                });

            modelBuilder.Entity("ApiPrueba.Models.ProtocoloTipoTerapia", b =>
                {
                    b.Property<int>("IdProtocoloTipoTerapia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProtocoloTipoTerapia"));

                    b.Property<int>("DuracionMinutosSugerida")
                        .HasColumnType("int");

                    b.Property<int>("IdProtocolo")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTerapia")
                        .HasColumnType("int");

                    b.Property<string>("Instrucciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumeroSesionesSugeridas")
                        .HasColumnType("int");

                    b.Property<int>("OrdenSecuencia")
                        .HasColumnType("int");

                    b.HasKey("IdProtocoloTipoTerapia");

                    b.HasIndex("IdTipoTerapia");

                    b.HasIndex("IdProtocolo", "IdTipoTerapia")
                        .IsUnique();

                    b.ToTable("ProtocoloTipoTerapias");
                });

            modelBuilder.Entity("ApiPrueba.Models.ProtocoloTratamiento", b =>
                {
                    b.Property<int>("IdProtocolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProtocolo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DuracionPorSesionMin")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("NumeroSesiones")
                        .HasColumnType("int");

                    b.Property<string>("Recomendaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdProtocolo");

                    b.ToTable("ProtocoloTratamientos");
                });

            modelBuilder.Entity("ApiPrueba.Models.ReservaCita", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<bool>("Confirmada")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<string>("MetodoConfirmacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TokenConfirmacion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdCita");

                    b.ToTable("ReservasCita");
                });

            modelBuilder.Entity("ApiPrueba.Models.SeguroMedico", b =>
                {
                    b.Property<int>("IdSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeguro"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cobertura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAseguradora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSeguro");

                    b.ToTable("SegurosMedicos");
                });

            modelBuilder.Entity("ApiPrueba.Models.TerapeutaEspecialidad", b =>
                {
                    b.Property<int>("IdTerapeutaEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTerapeutaEspecialidad"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCertificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdTerapeuta")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCertificado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTerapeutaEspecialidad");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdTerapeuta", "IdEspecialidad")
                        .IsUnique();

                    b.ToTable("TerapeutaEspecialidades");
                });

            modelBuilder.Entity("ApiPrueba.Models.TipoTerapia", b =>
                {
                    b.Property<int>("IdTipoTerapia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTerapia"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoTerapia");

                    b.ToTable("TipoTerapias");
                });

            modelBuilder.Entity("ApiPrueba.Models.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdTerapeuta")
                        .HasColumnType("int");

                    b.Property<string>("NombreTratamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanTratamientoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioTratamiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TerapeutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdTerapeuta");

                    b.HasIndex("PlanTratamientoId");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ApiPrueba.Models.TratamientoProtocolo", b =>
                {
                    b.Property<int>("IdTratamientoProtocolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamientoProtocolo"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProtocolo")
                        .HasColumnType("int");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("int");

                    b.Property<string>("NotasAplicacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrdenAplicacion")
                        .HasColumnType("int");

                    b.HasKey("IdTratamientoProtocolo");

                    b.HasIndex("IdProtocolo");

                    b.HasIndex("IdTratamiento", "IdProtocolo")
                        .IsUnique();

                    b.ToTable("TratamientoProtocolos");
                });

            modelBuilder.Entity("ApiPrueba.Models.TratamientoTipoTerapia", b =>
                {
                    b.Property<int>("IdTratamientoTipoTerapia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTratamientoTipoTerapia"));

                    b.Property<int>("DuracionMinutosPorSesion")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTerapia")
                        .HasColumnType("int");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSesionesAsignadas")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdTratamientoTipoTerapia");

                    b.HasIndex("IdTipoTerapia");

                    b.HasIndex("IdTratamiento", "IdTipoTerapia")
                        .IsUnique();

                    b.ToTable("TratamientoTipoTerapias");
                });

            modelBuilder.Entity("ApiPrueba.Models.Administrador", b =>
                {
                    b.HasBaseType("ApiPrueba.Models.Persona");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("ApiPrueba.Models.Paciente", b =>
                {
                    b.HasBaseType("ApiPrueba.Models.Persona");

                    b.Property<int?>("EpsId")
                        .HasColumnType("int");

                    b.Property<int?>("IdSeguroMedico")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDeAfiliacion")
                        .HasColumnType("int");

                    b.Property<int?>("SeguroMedicoIdSeguro")
                        .HasColumnType("int");

                    b.HasIndex("EpsId");

                    b.HasIndex("SeguroMedicoIdSeguro");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("ApiPrueba.Models.Terapeuta", b =>
                {
                    b.HasBaseType("ApiPrueba.Models.Persona");

                    b.Property<int>("AñosExperiencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TituloAcademico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Terapeuta");
                });

            modelBuilder.Entity("ApiPrueba.Models.AlertaAgenda", b =>
                {
                    b.HasOne("ApiPrueba.Models.Cita", "Cita")
                        .WithMany("Alertas")
                        .HasForeignKey("IdCita");

                    b.HasOne("ApiPrueba.Models.Terapeuta", "Terapeuta")
                        .WithMany("AlertasAgenda")
                        .HasForeignKey("IdTerapeuta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("ApiPrueba.Models.Cita", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Terapeuta", "Terapeuta")
                        .WithMany()
                        .HasForeignKey("IdTerapeuta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiPrueba.Models.Paciente", null)
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId");

                    b.HasOne("ApiPrueba.Models.Terapeuta", null)
                        .WithMany("Citas")
                        .HasForeignKey("TerapeutaId");

                    b.HasOne("ApiPrueba.Models.Tratamiento", null)
                        .WithMany("Citas")
                        .HasForeignKey("TratamientoId");

                    b.Navigation("Paciente");

                    b.Navigation("Terapeuta");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ApiPrueba.Models.ContactoEmergencia", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany("ContactosEmergencia")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ApiPrueba.Models.DetalleFactura", b =>
                {
                    b.HasOne("ApiPrueba.Models.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("ApiPrueba.Models.Diagnostico", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Terapeuta", "Terapeuta")
                        .WithMany()
                        .HasForeignKey("IdTerapeuta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiPrueba.Models.Paciente", null)
                        .WithMany("Diagnosticos")
                        .HasForeignKey("PacienteId");

                    b.HasOne("ApiPrueba.Models.Terapeuta", null)
                        .WithMany("Diagnosticos")
                        .HasForeignKey("TerapeutaId");

                    b.Navigation("Paciente");

                    b.Navigation("Terapeuta");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ApiPrueba.Models.DisponibilidadTerapeuta", b =>
                {
                    b.HasOne("ApiPrueba.Models.Terapeuta", "Terapeuta")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("IdTerapeuta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("ApiPrueba.Models.DocumentoPaciente", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany("Documentos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ApiPrueba.Models.EquipoSesion", b =>
                {
                    b.HasOne("ApiPrueba.Models.Equipo", "Equipo")
                        .WithMany("EquiposSesion")
                        .HasForeignKey("IdEquipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.ProtocoloTratamiento", "ProtocoloTratamiento")
                        .WithMany("EquiposSesion")
                        .HasForeignKey("IdProtocoloTratamiento");

                    b.Navigation("Equipo");

                    b.Navigation("ProtocoloTratamiento");
                });

            modelBuilder.Entity("ApiPrueba.Models.EvolucionPaciente", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany("Evoluciones")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ApiPrueba.Models.Factura", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany("Facturas")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("IdTratamiento");

                    b.Navigation("Paciente");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ApiPrueba.Models.HistorialMedico", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithOne("HistorialMedico")
                        .HasForeignKey("ApiPrueba.Models.HistorialMedico", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ApiPrueba.Models.NotaSesion", b =>
                {
                    b.HasOne("ApiPrueba.Models.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Paciente", null)
                        .WithMany("NotasSesion")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Cita");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ApiPrueba.Models.PlanTratamiento", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Terapeuta", "Terapeuta")
                        .WithMany()
                        .HasForeignKey("IdTerapeuta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Paciente", null)
                        .WithMany("PlanesTratamiento")
                        .HasForeignKey("PacienteId");

                    b.HasOne("ApiPrueba.Models.Terapeuta", null)
                        .WithMany("PlanesTratamiento")
                        .HasForeignKey("TerapeutaId");

                    b.Navigation("Paciente");

                    b.Navigation("Terapeuta");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ApiPrueba.Models.ProtocoloTipoTerapia", b =>
                {
                    b.HasOne("ApiPrueba.Models.ProtocoloTratamiento", "ProtocoloTratamiento")
                        .WithMany("ProtocoloTipoTerapias")
                        .HasForeignKey("IdProtocolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.TipoTerapia", "TipoTerapia")
                        .WithMany("ProtocolosTipoTerapia")
                        .HasForeignKey("IdTipoTerapia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProtocoloTratamiento");

                    b.Navigation("TipoTerapia");
                });

            modelBuilder.Entity("ApiPrueba.Models.ReservaCita", b =>
                {
                    b.HasOne("ApiPrueba.Models.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ApiPrueba.Models.TerapeutaEspecialidad", b =>
                {
                    b.HasOne("ApiPrueba.Models.Especialidad", "Especialidad")
                        .WithMany("TerapeutaEspecialidades")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Terapeuta", "Terapeuta")
                        .WithMany("TerapeutaEspecialidades")
                        .HasForeignKey("IdTerapeuta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("ApiPrueba.Models.Tratamiento", b =>
                {
                    b.HasOne("ApiPrueba.Models.Paciente", "Paciente")
                        .WithMany("Tratamientos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Terapeuta", "Terapeuta")
                        .WithMany()
                        .HasForeignKey("IdTerapeuta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.PlanTratamiento", "PlanTratamiento")
                        .WithMany()
                        .HasForeignKey("PlanTratamientoId");

                    b.HasOne("ApiPrueba.Models.Terapeuta", null)
                        .WithMany("Tratamientos")
                        .HasForeignKey("TerapeutaId");

                    b.Navigation("Paciente");

                    b.Navigation("PlanTratamiento");

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("ApiPrueba.Models.TratamientoProtocolo", b =>
                {
                    b.HasOne("ApiPrueba.Models.ProtocoloTratamiento", "ProtocoloTratamiento")
                        .WithMany("TratamientoProtocolos")
                        .HasForeignKey("IdProtocolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Tratamiento", "Tratamiento")
                        .WithMany("TratamientoProtocolos")
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProtocoloTratamiento");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ApiPrueba.Models.TratamientoTipoTerapia", b =>
                {
                    b.HasOne("ApiPrueba.Models.TipoTerapia", "TipoTerapia")
                        .WithMany("TratamientosTipoTerapia")
                        .HasForeignKey("IdTipoTerapia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPrueba.Models.Tratamiento", "Tratamiento")
                        .WithMany("TratamientoTipoTerapias")
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTerapia");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ApiPrueba.Models.Paciente", b =>
                {
                    b.HasOne("ApiPrueba.Models.EPS", "Eps")
                        .WithMany("Pacientes")
                        .HasForeignKey("EpsId");

                    b.HasOne("ApiPrueba.Models.SeguroMedico", "SeguroMedico")
                        .WithMany("Pacientes")
                        .HasForeignKey("SeguroMedicoIdSeguro");

                    b.Navigation("Eps");

                    b.Navigation("SeguroMedico");
                });

            modelBuilder.Entity("ApiPrueba.Models.Cita", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("ApiPrueba.Models.EPS", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiPrueba.Models.Equipo", b =>
                {
                    b.Navigation("EquiposSesion");
                });

            modelBuilder.Entity("ApiPrueba.Models.Especialidad", b =>
                {
                    b.Navigation("TerapeutaEspecialidades");
                });

            modelBuilder.Entity("ApiPrueba.Models.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ApiPrueba.Models.ProtocoloTratamiento", b =>
                {
                    b.Navigation("EquiposSesion");

                    b.Navigation("ProtocoloTipoTerapias");

                    b.Navigation("TratamientoProtocolos");
                });

            modelBuilder.Entity("ApiPrueba.Models.SeguroMedico", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("ApiPrueba.Models.TipoTerapia", b =>
                {
                    b.Navigation("ProtocolosTipoTerapia");

                    b.Navigation("TratamientosTipoTerapia");
                });

            modelBuilder.Entity("ApiPrueba.Models.Tratamiento", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("TratamientoProtocolos");

                    b.Navigation("TratamientoTipoTerapias");
                });

            modelBuilder.Entity("ApiPrueba.Models.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("ContactosEmergencia");

                    b.Navigation("Diagnosticos");

                    b.Navigation("Documentos");

                    b.Navigation("Evoluciones");

                    b.Navigation("Facturas");

                    b.Navigation("HistorialMedico");

                    b.Navigation("NotasSesion");

                    b.Navigation("PlanesTratamiento");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("ApiPrueba.Models.Terapeuta", b =>
                {
                    b.Navigation("AlertasAgenda");

                    b.Navigation("Citas");

                    b.Navigation("Diagnosticos");

                    b.Navigation("Disponibilidades");

                    b.Navigation("PlanesTratamiento");

                    b.Navigation("TerapeutaEspecialidades");

                    b.Navigation("Tratamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
