sonar.projectKey=kinesys
sonar.projectName=KineSys
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=kinesys/src,api/ApiPrueba
sonar.tests=kinesys/src,api/ApiPrueba.Tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/bin/**,**/obj/**,**/Migrations/**,**/*.Designer.cs,**/*ModelSnapshot.cs,**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,api/ApiPrueba.Tests/**/*.cs

sonar.javascript.lcov.reportPaths=kinesys/coverage/lcov.info
sonar.cs.opencover.reportsPaths=api/**/TestResults/**/coverage.opencover.xml
